name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: caesar test
      id: caesar-test
      uses: education/autograding-command-grader@v1
      with:
        test-name: caesar test
        setup-command: pip install pytest
        command: pytest tests.py
        timeout: 10
        max-score: 100
    - name: Autograding Reporter
      uses: education/autograding-grading-reporter@v1
      env:
        CAESAR-TEST_RESULTS: "${{steps.caesar-test.outputs.result}}"
      with:
        runners: caesar-test
